web:
    image: albovieira/homestead-docker
    restart: always
    ports:
        - "8080:80" # web
       # - "2222:22" # ssh
       # - "35730:35729" # live reload
       # - "9876:9876" # karma server
    environment:
      XDEBUG_CONFIG: "remote_host={ip}"
      PHP_IDE_CONFIG: "serverName={app}"

    volumes:
        - ./:/var/www
       # - ./sites:/etc/nginx/sites-enabled
        #- ~/.composer:/home/homestead/.composer # composer caching
        #- ~/.gitconfig:/home/homestead/.gitconfig # Git configuration ( access alias && Config )
        - ~/.ssh:/home/homestead/.ssh # Ssh keys for easy deployment inside the container
       # - ~/apps:/apps # all apps
       # - ~/apps/volumes/nginx/sites-available:/etc/nginx/sites-available # nginx sites ( in case you recreate the container )
       # - ~/apps/volumes/nginx/sites-enabled:/etc/nginx/sites-enabled # nginx sites ( in case you recreate the container )